### ISSUE TITLE
Allow updates to the outcome/partial resid before sample_one_iteration from R/Python interface

### ISSUE THREAD

**Issue by jaredsmurray** [StochasticTree/stochtree#87]
### Description
Allow updates to the outcome in/before sample_one_iteration from R/Python interface

### Ideas for Implementation / Expected Behavior

In the simples case we want to fit y = w'\beta + f(x) + eps; the relevant guts of the MCMC loop would be something like

    beta = sample_beta(...)
    
    forest_dataset$update_outcome(y - W%*%beta)
    
    forest_model$sample_one_iteration(
        forest_dataset, outcome, forest_samples, rng, feature_types, 
        outcome_model_type, leaf_prior_scale, var_weights, 
        global_var_samples[i], cutpoint_grid_size
    )

**Comment by andrewherren** [comment]
Great suggestion! Since the `outcome` object always maintains a partial residual with respect to forest and random effects predictions, I think we can probably add two methods to the outcome object for subtracting and adding values from that partial residual, so the workflow would look something like:

```
for (i in 1:mc) {
    if (i > 1) outcome$add_vector(W%*%beta)

    beta = sample_beta(...)

    outcome$subtract_vector(W%*%beta)

    forest_model$sample_one_iteration(
        forest_dataset, outcome, forest_samples, rng, feature_types, 
        outcome_model_type, leaf_prior_scale, var_weights, 
        global_var_samples[i], cutpoint_grid_size
    )
}
```

would that work?

**Comment by andrewherren** [comment]
This functionality has been implemented as sketched above. A demo of how this looks for an additive linear model is available [in the Custom Sampling Routine vignette](https://stochastictree.github.io/stochtree-r/articles/CustomSamplingRoutine.html#demo-4-supervised-learning-with-additive-linear-model).
