### ISSUE TITLE
Allow saving to json string as well as file 

### ISSUE THREAD

**Issue by awooddoughty** [StochasticTree/stochtree#88]
Right now the save functionality only allows [saving to a file](https://github.com/StochasticTree/stochtree/blob/5a40b091e7dcddfe23333655b511d03518c4984a/stochtree/forest.py#L43-L44), but it would be really useful to be able to dump to a json string to be able to store multiple artifacts together. e.g. something like [this](https://github.com/JingyuHe/XBART/blob/67b331c53ad5e1d56f702813a68a22411dd15eb7/python/xbart/xbart_python.py#L457-L461)

**Comment by andrewherren** [comment]
Thanks for opening this issue! I completely agree that `stochtree` needs this functionality. Returning JSON strings is part of what I'm working on to allow multi-core (parallel chain) forest sampling, so it's a high priority on our end. I'll have a PR merged that supports this either by the end of this week or mid-next week. I'll link back to this issue once the PR is merged to keep you posted.

**Comment by andrewherren** [comment]
Following up to say that this is now supported! The [dump_json_string](https://github.com/StochasticTree/stochtree/blob/40c7f8696b25344f871a991457f4adda5232ccfa/stochtree/forest.py#L49) method converts a `ForestContainer` object to a JSON string and the [load_from_json_string](https://github.com/StochasticTree/stochtree/blob/40c7f8696b25344f871a991457f4adda5232ccfa/stochtree/forest.py#L52) method resets a `ForestContainer` object and loads it from a provided JSON string. 

You can see an example of this serialization/deserialization in action in [one of our unit tests](https://github.com/StochasticTree/stochtree/blob/40c7f8696b25344f871a991457f4adda5232ccfa/test/python/test_json.py#L160).
