### ISSUE TITLE
Error in R stochtree::bcf when pi_train is not provided

### ISSUE THREAD

**Issue by drizmiz** [StochasticTree/stochtree#90]
When calling `stochtree::bcf` in R without providing the parameters `pi_train` and `pi_test`, an error occurs:
```
Error in rep(1/num_cov_orig, ncol(pi_train)) : invalid 'times' argument
```

After investigation, I found that if the vector `pi_train` is provided, the function transforms it into a matrix. However, when `pi_train` is not provided and is generated within the function, this step is skipped, so it does not have a column count. Additionally, even when `pi_train` is provided, after transformation, `ncol(pi_train)` is always `1`, which does not seem to be the intended behavior.

**Comment by andrewherren** [comment]
Thanks for bringing this up! From what you describe, it should be a quick fix. I'll add a unit test for this use case (pi not provided) and let you know when the fix is merged.

**Comment by andrewherren** [comment]
Hi there! This should be addressed now in the latest version of `stochtree`!
